=== leot03/Apprendre_xml_snir2/00_XML/TD1_ObjectAuChoix/public_html/systemesExploitation.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT se (type+)>
<!ELEMENT type (windows*, linux*, macos*)>
<!ELEMENT windows (version?, dateCreation?, derniereMaj?)>
<!ELEMENT linux (version?, dateCreation?, derniereMaj?)>
<!ELEMENT macos (version?, dateCreation?, derniereMaj?)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT dateCreation (#PCDATA)>
<!ELEMENT derniereMaj (#PCDATA)>

<!ATTLIST version nom CDATA #IMPLIED>

=== leot03/Apprendre_xml_snir2/00_XML/TD1_ObjectAuChoix/public_html/systemesExploitation.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE lycee SYSTEM 'systemesExploitation.dtd'>
<?xml-stylesheet href="style.css" type="text/css"?>


<se>
    <type>
        <windows>
            <version>Windows 11</version>
            <dateCreation>5 Octobre 2021</dateCreation>
            <derniereMaj>02 sept 2022</derniereMaj>
        </windows>
        <linux>
            <version>Distro</version>
            <dateCreation>8 novembre 2017</dateCreation>
            <derniereMaj>05 sept 2022</derniereMaj>
        </linux>
        <macos>
            <version>Ventura</version>
            <dateCreation>Septembre 2022</dateCreation>
            <derniereMaj>Non d√©finie</derniereMaj>
        </macos>
    </type>
</se>
